28-08-2021 10:30:23 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 14:49:35 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 14:49:35 - [INFO] -  exploration - (exploration.py).countplots(line 16) - countplots successfully.
28-08-2021 14:49:36 - [INFO] -  exploration - (exploration.py).violinplots(line 26) - violinplots successfully
28-08-2021 14:49:37 - [INFO] -  exploration - (exploration.py).violinplots(line 26) - violinplots successfully
28-08-2021 14:49:37 - [INFO] -  exploration - (exploration.py).violinplots(line 26) - violinplots successfully
28-08-2021 14:49:38 - [INFO] -  exploration - (exploration.py).boxplots(line 42) - boxplots successfully
28-08-2021 14:49:39 - [INFO] -  exploration - (exploration.py).jointplots(line 48) - jointplots successfully
28-08-2021 14:49:42 - [INFO] -  exploration - (exploration.py).pairplots(line 59) - pairplots successfully
28-08-2021 14:49:45 - [INFO] -  exploration - (exploration.py).swarmplots(line 67) - swarmplots successfully
28-08-2021 14:49:51 - [INFO] -  exploration - (exploration.py).swarmplots(line 67) - swarmplots successfully
28-08-2021 14:49:55 - [INFO] -  exploration - (exploration.py).swarmplots(line 67) - swarmplots successfully
28-08-2021 14:49:56 - [INFO] -  exploration - (exploration.py).correlation(line 74) - plots correlation map successfully
28-08-2021 14:49:59 - [INFO] -  exploration - (exploration.py).correlation(line 74) - plots correlation map successfully
28-08-2021 15:03:41 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:05:20 - [ERROR] -  structure - (structure.py).drawgraph(line 17) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Desktop/Industry - Casualty Challenge/scripts/structure.py", line 12, in drawgraph
    viz = plot_structure( sm, graph_attributes={"scale": "2.0","size": "2.5"}, all_node_attributes=NODE_STYLE.WEAK, all_edge_attributes=EDGE_STYLE.WEAK)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 105, in plot_structure
    sm, all_node_attributes, all_edge_attributes, node_attributes, edge_attributes
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 197, in _add_attributes
    for node in _sm.nodes:
AttributeError: 'NoneType' object has no attribute 'nodes'
28-08-2021 15:06:25 - [ERROR] -  structure - (structure.py).drawgraph(line 17) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Desktop/Industry - Casualty Challenge/scripts/structure.py", line 12, in drawgraph
    viz = plot_structure( sm, graph_attributes={"scale": "2.0","size": "2.5"}, all_node_attributes=NODE_STYLE.WEAK, all_edge_attributes=EDGE_STYLE.WEAK)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 105, in plot_structure
    sm, all_node_attributes, all_edge_attributes, node_attributes, edge_attributes
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 197, in _add_attributes
    for node in _sm.nodes:
AttributeError: 'NoneType' object has no attribute 'nodes'
28-08-2021 15:06:33 - [ERROR] -  structure - (structure.py).drawgraph(line 17) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Desktop/Industry - Casualty Challenge/scripts/structure.py", line 12, in drawgraph
    viz = plot_structure( sm, graph_attributes={"scale": "2.0","size": "2.5"}, all_node_attributes=NODE_STYLE.WEAK, all_edge_attributes=EDGE_STYLE.WEAK)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 105, in plot_structure
    sm, all_node_attributes, all_edge_attributes, node_attributes, edge_attributes
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 197, in _add_attributes
    for node in _sm.nodes:
AttributeError: 'NoneType' object has no attribute 'nodes'
28-08-2021 15:06:48 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:08:08 - [INFO] -  structure - (structure.py).drawgraph(line 14) - plots causal graph successfully
28-08-2021 15:09:08 - [INFO] -  structure - (structure.py).drawgraph(line 14) - plots causal graph successfully
28-08-2021 15:09:19 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:10:21 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:11:23 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:11:42 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:15:32 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:15:32 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:17:01 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:17:01 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:21:49 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:21:49 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:22:56 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:22:56 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:24:47 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:24:47 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:25:05 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:26:31 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:28:05 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:28:22 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:28:42 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:30:01 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:31:28 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:37:49 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:53:51 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 16:58:09 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
28-08-2021 18:42:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:42:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:42:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:44:44 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:44:44 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:44:44 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:48:06 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:48:06 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:48:06 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:51:21 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:51:21 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:51:21 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:53:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:53:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:53:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:54:50 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:54:50 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:54:50 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:57:59 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:57:59 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:57:59 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:59:55 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:59:55 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:59:55 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:02:23 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:02:23 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:02:23 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:03:13 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:03:13 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:03:13 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:05:39 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:05:39 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:05:39 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 22:10:14 - [ERROR] -  file_read - (file_read.py).read_csv(line 25) - File not found.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/file_read.py", line 20, in read_csv
    df = pd.read_csv(csv_path, na_values=missing_values)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '../input/data.csv'
28-08-2021 22:14:24 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 22:14:36 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
28-08-2021 22:17:59 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
28-08-2021 22:18:58 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
28-08-2021 22:18:58 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
28-08-2021 22:19:49 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 08:50:21 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 08:50:21 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 08:50:22 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 08:51:40 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:52:33 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:53:01 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:53:32 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:53:49 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:54:11 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:54:50 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:55:23 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:55:51 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:55:51 - [ERROR] -  structure - (structure.py).drawgraph(line 22) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 16, in drawgraph
    sm.remove_edges_below_threshold(0.8)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 08:57:57 - [ERROR] -  structure - (structure.py).drawgraph(line 22) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 16, in drawgraph
    sm.remove_edges_below_threshold(0.8)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 08:57:59 - [ERROR] -  structure - (structure.py).drawgraph(line 22) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 16, in drawgraph
    sm.remove_edges_below_threshold(0.8)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 09:05:05 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 09:05:05 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 09:05:05 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 09:06:52 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:08:08 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:08:43 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:09:05 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:09:23 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:09:45 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:10:31 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:11:02 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:11:42 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:11:42 - [INFO] -  structure - (structure.py).drawgraphs(line 27) - plots causal graph successfully
<<<<<<< HEAD
29-08-2021 09:42:14 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 09:42:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 09:42:18 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 09:42:18 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
=======
29-08-2021 09:45:07 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 09:45:11 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 09:46:35 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 09:46:35 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 09:47:05 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 09:50:12 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 09:50:12 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 09:50:12 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 09:50:12 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 09:50:12 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 09:50:12 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 09:50:12 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 09:50:13 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:50:13 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:52:43 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:52:43 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:54:15 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:54:15 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:55:27 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:55:27 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:56:06 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:56:06 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:57:22 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:57:22 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:00:42 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:00:42 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:02:28 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:02:28 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:03:05 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:03:05 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:03:06 - [INFO] -  structure - (structure.py).drawgraphs(line 27) - plots causal graph successfully
29-08-2021 10:03:06 - [INFO] -  structure - (structure.py).drawgraphs(line 27) - plots causal graph successfully
29-08-2021 10:33:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:33:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:33:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:33:00 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:33:00 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:33:00 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:33:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:33:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:33:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:33:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:33:01 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:33:01 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:33:01 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:36:34 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:36:34 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:36:34 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:36:34 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:36:34 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:36:34 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:36:34 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:36:34 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:36:34 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:36:34 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:36:34 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:36:34 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:36:34 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:36:35 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:36:35 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:36:35 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:36:35 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:41:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:41:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:41:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:41:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:41:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:41:47 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:41:47 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:41:47 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:41:47 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:41:47 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:41:47 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:41:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:46:11 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:46:11 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:46:11 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:46:11 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:46:11 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 10:46:42 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:46:42 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:46:42 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:46:42 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:46:42 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:46:42 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:46:42 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:46:42 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:46:42 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:46:42 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:46:42 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:46:42 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:46:42 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:46:42 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:46:42 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:46:42 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:46:42 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:46:42 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:46:42 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:46:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:46:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:46:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:46:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:46:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:46:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:50:46 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:50:46 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:50:46 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:50:46 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:50:46 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:50:46 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:50:46 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:50:46 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:50:46 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:50:46 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:50:46 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:50:46 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:50:46 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:50:46 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:50:46 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:50:46 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:50:46 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:50:46 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:50:46 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:50:46 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:50:46 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:50:46 - [INFO] -  randomforest - (randomforest.py).splitdata(line 22) - splits data successfully.
29-08-2021 10:50:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:50:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:50:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:50:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:50:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:50:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:50:47 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:53:52 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:53:52 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:53:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 10:53:53 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:56:37 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 10:56:37 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 10:56:37 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 10:56:37 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 10:57:57 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 10:57:58 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph.png'
29-08-2021 13:41:22 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 13:41:22 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 13:41:22 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 13:41:23 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 13:42:41 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:00:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 14:00:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 14:00:00 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 14:00:00 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 14:00:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 14:00:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 14:00:00 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 14:00:00 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 14:01:49 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:01:49 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:23:52 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:23:52 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:23:52 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph1.png'
29-08-2021 14:23:52 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph1.png'
29-08-2021 14:24:30 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:24:30 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:26:41 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:26:41 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:30:40 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:30:40 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:54:05 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 14:54:05 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 14:54:05 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 14:54:05 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 14:54:05 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 14:54:05 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 14:54:05 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 14:54:05 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 14:54:05 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 14:54:06 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 14:54:06 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 14:54:06 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 14:55:56 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:55:56 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:55:56 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:55:56 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph.png'
29-08-2021 14:55:56 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph.png'
29-08-2021 14:55:56 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph.png'
29-08-2021 14:57:47 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:57:47 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:57:47 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:58:40 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:58:40 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:58:40 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:58:40 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph2.png'
29-08-2021 14:58:40 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph2.png'
29-08-2021 14:58:40 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph2.png'
29-08-2021 14:59:05 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:59:05 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:59:05 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:59:05 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph3.png'
29-08-2021 14:59:05 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph3.png'
29-08-2021 14:59:05 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph3.png'
29-08-2021 14:59:30 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:59:30 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:59:30 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 14:59:30 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph4.png'
29-08-2021 14:59:30 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph4.png'
29-08-2021 14:59:30 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph4.png'
29-08-2021 15:05:25 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:05:25 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:05:25 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:05:25 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph'
29-08-2021 15:05:25 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph'
29-08-2021 15:05:25 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 29, in drawgraph
    mlflow.log_artifact(path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 550, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/client.py", line 931, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 325, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 38, in log_artifact
    shutil.copyfile(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/home/neba/.conda/envs/feature/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../output/graph'
29-08-2021 15:05:44 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:05:44 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:05:44 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:34:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 15:34:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 15:34:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 15:34:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 15:34:00 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 15:34:00 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 15:34:00 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 15:34:00 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 15:34:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 15:34:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 15:34:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 15:34:00 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 15:34:01 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 15:34:01 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 15:34:01 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 15:34:01 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 15:37:33 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:37:33 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:37:33 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:37:33 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:38:49 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:38:49 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:38:49 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:38:49 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:39:25 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:39:25 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:39:25 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:39:25 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:39:51 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:39:51 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:39:51 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:39:51 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:40:14 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:40:14 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:40:14 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:40:14 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:45:22 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:45:22 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:45:22 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:45:22 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 15:49:43 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 15:49:43 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 15:49:43 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 15:49:43 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 15:49:43 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 15:49:43 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 15:49:43 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 15:49:43 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 15:49:43 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 15:49:43 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 15:49:43 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 15:51:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:51:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:51:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:51:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:51:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:07 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:38 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:38 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:38 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:38 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:52:38 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:01 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:01 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:01 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:01 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:01 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:17 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:17 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:17 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:17 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:17 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:41 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:41 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:41 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:41 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:53:41 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:18 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:18 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:18 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:18 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:18 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:48 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:48 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:48 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:48 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:54:48 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:55:31 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:55:31 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:55:31 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:55:31 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:55:31 - [INFO] -  structure - (structure.py).drawgraph(line 23) - plots causal graph successfully
29-08-2021 15:55:31 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 20, in drawgraph
    mlflow.set_experiment('Breast cancer Causality')
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 15:55:31 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 20, in drawgraph
    mlflow.set_experiment('Breast cancer Causality')
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 15:55:31 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 20, in drawgraph
    mlflow.set_experiment('Breast cancer Causality')
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 15:55:31 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 20, in drawgraph
    mlflow.set_experiment('Breast cancer Causality')
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 15:55:31 - [ERROR] -  structure - (structure.py).drawgraph(line 34) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 20, in drawgraph
    mlflow.set_experiment('Breast cancer Causality')
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 15:58:31 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:58:31 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:58:31 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:58:31 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:58:31 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:28 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:28 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:28 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:28 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:28 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:39 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:39 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:39 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:39 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 15:59:39 - [INFO] -  structure - (structure.py).drawgraphs(line 53) - plots causal graph successfully
29-08-2021 16:01:15 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:15 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:15 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:15 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:15 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:15 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:19 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:19 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:19 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:19 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:19 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:19 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:01:19 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:04:31 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:04:31 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:04:31 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:04:31 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:04:31 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:04:31 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:04:31 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:04:31 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:04:31 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:08:30 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:08:30 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:08:30 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:08:30 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:08:30 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:08:36 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:08:36 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:08:36 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:08:36 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:08:36 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:08:36 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:08:41 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:09:00 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:10:31 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 48) - failed to do confusion matrix.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/randomforest.py", line 41, in accuracy
TypeError: randomforest() missing 1 required positional argument: 'y_train'
29-08-2021 16:13:40 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:13:40 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:13:40 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:13:40 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:13:40 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:13:40 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:13:50 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:13:50 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:13:50 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:13:50 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:13:50 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:13:50 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:13:50 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:13:55 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:14:10 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:16:34 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:14 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:17:14 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:17:14 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:17:14 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:17:14 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:17:14 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:17:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:17:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:17:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:17:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:17:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:17:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:17:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:17:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:24 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:17:38 - [ERROR] -  randomforest - (randomforest.py).randomforest(line 34) - train model.
NoneType: None
29-08-2021 16:23:44 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:23:44 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:23:44 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:23:44 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:23:44 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:23:44 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:23:44 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:23:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:23:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:23:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:23:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:23:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:23:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:23:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:23:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:23:47 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:23:52 - [INFO] -  randomforest - (randomforest.py).splitdata(line 23) - splits data successfully.
29-08-2021 16:28:56 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:29:02 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:29:09 - [INFO] -  randomforest - (randomforest.py).splitdata(line 25) - splits data successfully.
29-08-2021 16:29:19 - [INFO] -  randomforest - (randomforest.py).splitdata(line 25) - splits data successfully.
29-08-2021 16:29:19 - [INFO] -  randomforest - (randomforest.py).splitdata(line 25) - splits data successfully.
29-08-2021 16:30:14 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 16:30:14 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 16:30:14 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 16:30:25 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 16:30:25 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 16:30:25 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 16:30:25 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 57) - plot confusion matrix.
NoneType: None
29-08-2021 16:30:25 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 57) - plot confusion matrix.
NoneType: None
29-08-2021 16:30:25 - [ERROR] -  randomforest - (randomforest.py).accuracy(line 57) - plot confusion matrix.
NoneType: None
29-08-2021 16:57:18 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 16:57:28 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 16:59:08 - [INFO] -  randomforest - (randomforest.py).splitdata(line 25) - splits data successfully.
29-08-2021 17:02:12 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 17:02:12 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 17:02:18 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 17:02:18 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 17:02:18 - [INFO] -  randomforest - (randomforest.py).accuracy(line 57) - plot confusion matrix.
29-08-2021 17:02:18 - [INFO] -  randomforest - (randomforest.py).accuracy(line 57) - plot confusion matrix.
29-08-2021 17:11:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 17:11:00 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 17:11:13 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 17:11:13 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 17:11:13 - [INFO] -  randomforest - (randomforest.py).randomforest(line 37) - train model.
29-08-2021 17:12:02 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 17:12:04 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 17:12:06 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 17:12:06 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 17:12:09 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 17:12:09 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 17:12:09 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 17:12:42 - [INFO] -  logistic - (logistic.py).splitdata(line 24) - splits data successfully.
29-08-2021 17:12:42 - [INFO] -  logistic - (logistic.py).splitdata(line 24) - splits data successfully.
29-08-2021 17:14:43 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
29-08-2021 17:14:43 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
29-08-2021 17:14:43 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
29-08-2021 17:14:43 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
29-08-2021 17:14:57 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
29-08-2021 17:14:57 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
29-08-2021 17:14:57 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
29-08-2021 17:14:57 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
29-08-2021 17:14:57 - [INFO] -  logistic - (logistic.py).accuracy(line 56) - plot confusion matrix.
29-08-2021 17:14:57 - [INFO] -  logistic - (logistic.py).accuracy(line 56) - plot confusion matrix.
29-08-2021 17:14:57 - [INFO] -  logistic - (logistic.py).accuracy(line 56) - plot confusion matrix.
29-08-2021 17:14:57 - [INFO] -  logistic - (logistic.py).accuracy(line 56) - plot confusion matrix.
>>>>>>> 899e44d379c8165eeb9bd9c8b5d7c8248f053459
30-08-2021 16:43:09 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
30-08-2021 16:43:18 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
30-08-2021 16:43:50 - [INFO] -  logistic - (logistic.py).splitdata(line 24) - splits data successfully.
30-08-2021 16:43:50 - [INFO] -  logistic - (logistic.py).splitdata(line 24) - splits data successfully.
30-08-2021 16:44:06 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
30-08-2021 16:44:06 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
30-08-2021 16:44:06 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
30-08-2021 16:44:20 - [INFO] -  logistic - (logistic.py).splitdata(line 24) - splits data successfully.
30-08-2021 16:44:20 - [INFO] -  logistic - (logistic.py).splitdata(line 24) - splits data successfully.
30-08-2021 16:44:20 - [INFO] -  logistic - (logistic.py).splitdata(line 24) - splits data successfully.
30-08-2021 16:44:25 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
30-08-2021 16:44:25 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
30-08-2021 16:44:25 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
30-08-2021 16:44:30 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
30-08-2021 16:44:30 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
30-08-2021 16:44:30 - [INFO] -  logistic - (logistic.py).logistic(line 36) - train model.
30-08-2021 16:44:31 - [INFO] -  logistic - (logistic.py).accuracy(line 56) - plot confusion matrix.
30-08-2021 16:44:31 - [INFO] -  logistic - (logistic.py).accuracy(line 56) - plot confusion matrix.
30-08-2021 16:44:31 - [INFO] -  logistic - (logistic.py).accuracy(line 56) - plot confusion matrix.
30-08-2021 17:42:32 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
30-08-2021 17:44:55 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
30-08-2021 17:44:55 - [INFO] -  __main__ - (experiment.py).splitdata(line 53) - splits data successfully.
30-08-2021 17:44:57 - [INFO] -  __main__ - (experiment.py).logistic(line 65) - train model.
30-08-2021 17:44:59 - [INFO] -  __main__ - (experiment.py).accuracy(line 85) - plot confusion matrix.
