28-08-2021 10:30:23 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 14:49:35 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 14:49:35 - [INFO] -  exploration - (exploration.py).countplots(line 16) - countplots successfully.
28-08-2021 14:49:36 - [INFO] -  exploration - (exploration.py).violinplots(line 26) - violinplots successfully
28-08-2021 14:49:37 - [INFO] -  exploration - (exploration.py).violinplots(line 26) - violinplots successfully
28-08-2021 14:49:37 - [INFO] -  exploration - (exploration.py).violinplots(line 26) - violinplots successfully
28-08-2021 14:49:38 - [INFO] -  exploration - (exploration.py).boxplots(line 42) - boxplots successfully
28-08-2021 14:49:39 - [INFO] -  exploration - (exploration.py).jointplots(line 48) - jointplots successfully
28-08-2021 14:49:42 - [INFO] -  exploration - (exploration.py).pairplots(line 59) - pairplots successfully
28-08-2021 14:49:45 - [INFO] -  exploration - (exploration.py).swarmplots(line 67) - swarmplots successfully
28-08-2021 14:49:51 - [INFO] -  exploration - (exploration.py).swarmplots(line 67) - swarmplots successfully
28-08-2021 14:49:55 - [INFO] -  exploration - (exploration.py).swarmplots(line 67) - swarmplots successfully
28-08-2021 14:49:56 - [INFO] -  exploration - (exploration.py).correlation(line 74) - plots correlation map successfully
28-08-2021 14:49:59 - [INFO] -  exploration - (exploration.py).correlation(line 74) - plots correlation map successfully
28-08-2021 15:03:41 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:05:20 - [ERROR] -  structure - (structure.py).drawgraph(line 17) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Desktop/Industry - Casualty Challenge/scripts/structure.py", line 12, in drawgraph
    viz = plot_structure( sm, graph_attributes={"scale": "2.0","size": "2.5"}, all_node_attributes=NODE_STYLE.WEAK, all_edge_attributes=EDGE_STYLE.WEAK)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 105, in plot_structure
    sm, all_node_attributes, all_edge_attributes, node_attributes, edge_attributes
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 197, in _add_attributes
    for node in _sm.nodes:
AttributeError: 'NoneType' object has no attribute 'nodes'
28-08-2021 15:06:25 - [ERROR] -  structure - (structure.py).drawgraph(line 17) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Desktop/Industry - Casualty Challenge/scripts/structure.py", line 12, in drawgraph
    viz = plot_structure( sm, graph_attributes={"scale": "2.0","size": "2.5"}, all_node_attributes=NODE_STYLE.WEAK, all_edge_attributes=EDGE_STYLE.WEAK)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 105, in plot_structure
    sm, all_node_attributes, all_edge_attributes, node_attributes, edge_attributes
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 197, in _add_attributes
    for node in _sm.nodes:
AttributeError: 'NoneType' object has no attribute 'nodes'
28-08-2021 15:06:33 - [ERROR] -  structure - (structure.py).drawgraph(line 17) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Desktop/Industry - Casualty Challenge/scripts/structure.py", line 12, in drawgraph
    viz = plot_structure( sm, graph_attributes={"scale": "2.0","size": "2.5"}, all_node_attributes=NODE_STYLE.WEAK, all_edge_attributes=EDGE_STYLE.WEAK)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 105, in plot_structure
    sm, all_node_attributes, all_edge_attributes, node_attributes, edge_attributes
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/plots/plots.py", line 197, in _add_attributes
    for node in _sm.nodes:
AttributeError: 'NoneType' object has no attribute 'nodes'
28-08-2021 15:06:48 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:08:08 - [INFO] -  structure - (structure.py).drawgraph(line 14) - plots causal graph successfully
28-08-2021 15:09:08 - [INFO] -  structure - (structure.py).drawgraph(line 14) - plots causal graph successfully
28-08-2021 15:09:19 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:10:21 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:11:23 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:11:42 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:15:32 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:15:32 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:17:01 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:17:01 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:21:49 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:21:49 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:22:56 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:22:56 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:24:47 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:24:47 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:25:05 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:26:31 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:28:05 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:28:22 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:28:42 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 15:30:01 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:31:28 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:37:49 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 15:53:51 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 16:58:09 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
28-08-2021 18:42:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:42:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:42:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:44:44 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:44:44 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:44:44 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:48:06 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:48:06 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:48:06 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:51:21 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:51:21 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:51:21 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:53:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:53:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:53:38 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:54:50 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:54:50 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:54:50 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:57:59 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:57:59 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:57:59 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:59:55 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:59:55 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 18:59:55 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:02:23 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:02:23 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:02:23 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:03:13 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:03:13 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:03:13 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:05:39 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:05:39 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 19:05:39 - [INFO] -  structure - (structure.py).drawgraph(line 13) - plots causal graph successfully
28-08-2021 22:10:14 - [ERROR] -  file_read - (file_read.py).read_csv(line 25) - File not found.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/file_read.py", line 20, in read_csv
    df = pd.read_csv(csv_path, na_values=missing_values)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '../input/data.csv'
28-08-2021 22:14:24 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
28-08-2021 22:14:36 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
28-08-2021 22:17:59 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
28-08-2021 22:18:58 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
28-08-2021 22:18:58 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
28-08-2021 22:19:49 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 08:50:21 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 08:50:21 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 08:50:22 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 08:51:40 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:52:33 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:53:01 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:53:32 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:53:49 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:54:11 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:54:50 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:55:23 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:55:51 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 08:55:51 - [ERROR] -  structure - (structure.py).drawgraph(line 22) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 16, in drawgraph
    sm.remove_edges_below_threshold(0.8)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 08:57:57 - [ERROR] -  structure - (structure.py).drawgraph(line 22) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 16, in drawgraph
    sm.remove_edges_below_threshold(0.8)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 08:57:59 - [ERROR] -  structure - (structure.py).drawgraph(line 22) - plots causal graph  failed.
Traceback (most recent call last):
  File "/home/neba/Downloads/Industry---Casualty-Challenge/scripts/structure.py", line 16, in drawgraph
    sm.remove_edges_below_threshold(0.8)
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in remove_edges_below_threshold
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
  File "/home/neba/.conda/envs/feature/lib/python3.7/site-packages/causalnex/structure/structuremodel.py", line 252, in <listcomp>
    [(u, v) for u, v, w in self.edges(data="weight") if np.abs(w) < threshold]
TypeError: bad operand type for abs(): 'NoneType'
29-08-2021 09:05:05 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 09:05:05 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 09:05:05 - [INFO] -  file_read - (file_read.py).to_csv(line 13) - Csv file saved in ../input/extracted.csv.
29-08-2021 09:06:52 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:08:08 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:08:43 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:09:05 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:09:23 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:09:45 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:10:31 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:11:02 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:11:42 - [INFO] -  structure - (structure.py).drawgraph(line 18) - plots causal graph successfully
29-08-2021 09:11:42 - [INFO] -  structure - (structure.py).drawgraphs(line 27) - plots causal graph successfully
29-08-2021 09:42:14 - [INFO] -  file_read - (file_read.py).read_csv(line 21) - Csv file read from ../input/data.csv.
29-08-2021 09:42:16 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 09:42:18 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
29-08-2021 09:42:18 - [INFO] -  preprocess - (preprocess.py).label_encode(line 34) - encodes label for non_numeric successfully
